//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Party.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutUsers
    {
        public int UsersInfoID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> AddressID { get; set; }
    
        public virtual Adress Adress { get; set; }
        public virtual Users Users { get; set; }
    }
}
