//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Party.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adress()
        {
            this.AboutUsers = new HashSet<AboutUsers>();
        }
    
        public int AdressID { get; set; }
        public string Road { get; set; }
        public string Street { get; set; }
        public string Neighborhood { get; set; }
        public string ApartmenNo { get; set; }
        public string Floor { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public int UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AboutUsers> AboutUsers { get; set; }
        public virtual Users Users { get; set; }
    }
}
