//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Party.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surveys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Surveys()
        {
            this.Questions = new HashSet<Questions>();
        }
    
        public int SurveyID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> PrivacyID { get; set; }
        public string UploadDate { get; set; }
        public Nullable<int> Like { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> QuestionsID { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual PrivacyStatement PrivacyStatement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Questions> Questions { get; set; }
        public virtual Users Users { get; set; }
    }
}
